services:
  web:
    build: .
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis
    environment:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"